CREATE TABLE `match_events_live` (
  `id` bigint(20) NOT NULL,
  `event_id` bigint(20) DEFAULT NULL,
  `minute` int(11) DEFAULT NULL,
  `second` float DEFAULT NULL,
  `team_id` bigint(20) DEFAULT NULL,
  `team_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `player_id` bigint(20) DEFAULT NULL,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `x` float DEFAULT NULL,
  `y` float DEFAULT NULL,
  `end_x` float DEFAULT NULL,
  `end_y` float DEFAULT NULL,
  `is_touch` tinyint(1) DEFAULT NULL,
  `is_shot` tinyint(1) DEFAULT NULL,
  `is_goal` tinyint(1) DEFAULT NULL,
  `card_type` tinyint(1) DEFAULT NULL,
  `type_display_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `outcome_type_display_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `period_display_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `match_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `event_timestamp` datetime DEFAULT NULL,
  SORT KEY `minute` (`minute`,`second`),
  KEY `is_shot` (`is_shot`) USING HASH,
  KEY `is_goal` (`is_goal`) USING HASH,
  KEY `is_touch` (`is_touch`) USING HASH,
  KEY `player_name` (`player_name`) USING HASH,
  KEY `team_name` (`team_name`) USING HASH,
  KEY `type_display_name` (`type_display_name`) USING HASH,
  PRIMARY KEY (`id`),
  SHARD KEY `__SHARDKEY` (`id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES,NO_AUTO_CREATE_USER' CHARACTER SET=`utf8mb4` COLLATE=`utf8mb4_general_ci`